const assert = require('assert');

describe('Teambuilder tables: gen5sgss overrides', function () {
  it('should include gen5sgss with overrideSpeciesData for butterfree and pikachu', function () {
    // This file is generated by build-indexes and is required by the normal test task
    // The import will fail if the build hasn't been run, so the project's test script runs build first
    const tb = require('../play.pokemonshowdown.com/data/teambuilder-tables.js').BattleTeambuilderTable;

    assert(tb, 'BattleTeambuilderTable is present');
    assert(tb.gen5sgss, 'gen5sgss entry should exist');

    const overrides = tb.gen5sgss.overrideSpeciesData;
    assert(overrides, 'gen5sgss.overrideSpeciesData should exist');

    // Sample checks against known mod overrides present in caches/pokemon-showdown/data/mods/gen5sgss/pokedex.ts
    assert(overrides.butterfree, 'butterfree override should exist');
    assert.strictEqual(overrides.butterfree.abilities && overrides.butterfree.abilities[0], 'Tinted Lens');
    assert.deepStrictEqual(overrides.butterfree.baseStats, {hp:60,atk:45,def:50,spa:100,spd:100,spe:80});

    assert(overrides.pikachu, 'pikachu override should exist');
    assert.strictEqual(overrides.pikachu.abilities && overrides.pikachu.abilities[0], 'Lightningrod');
    assert.deepStrictEqual(overrides.pikachu.baseStats, {hp:35,atk:65,def:40,spa:60,spd:50,spe:95});
  });
});
